<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="B2-LAP-SSURESH7" name="com.prevail.shopnav.Footer" tests="7" failures="0" timestamp="18 Dec 2017 12:26:44 GMT" time="243.218" errors="2">
  <testcase name="TC02_Footer_CustomerServiceSection_LinkNavigation" time="21.415" classname="com.prevail.shopnav.Footer"/>
  <testcase name="TC01_Footer_AccountSectionLinks_Navigation" time="24.920" classname="com.prevail.shopnav.Footer">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 3, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.prevail.shopnav.Footer.TC01_Footer_AccountSectionLinks_Navigation(Footer.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC01_Footer_AccountSectionLinks_Navigation -->
  <testcase name="TC06_Footer_CustomerServiceSection_LinkNavigation_RegisteredUser" time="13.953" classname="com.prevail.shopnav.Footer"/>
  <testcase name="TC00_GlobalFooter_UI" time="5.769" classname="com.prevail.shopnav.Footer"/>
  <testcase name="TC05_Footer_CustomerServiceSection_LinkNavigation_RegisteredUser" time="17.699" classname="com.prevail.shopnav.Footer"/>
  <testcase name="TC03_Footer_CustomerServiceSection_LinkNavigation" time="34.696" classname="com.prevail.shopnav.Footer"/>
  <testcase name="TC04_Footer_AccountSectionLinks_Navigation_RegisteredUser" time="124.766" classname="com.prevail.shopnav.Footer">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.prevail.shopnav.Footer.TC04_Footer_AccountSectionLinks_Navigation_RegisteredUser(Footer.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC04_Footer_AccountSectionLinks_Navigation_RegisteredUser -->
</testsuite> <!-- com.prevail.shopnav.Footer -->
