<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="B2-LAP-SSURESH7" name="com.prevail.shopnav.HomePage" tests="5" failures="1" timestamp="18 Dec 2017 10:51:13 GMT" time="65.686" errors="0">
  <testcase name="TC02_HomePage_UIonmousehoverofrootcategories" time="2.954" classname="com.prevail.shopnav.HomePage"/>
  <testcase name="TC00_HomePage_CategoryNavigation" time="36.064" classname="com.prevail.shopnav.HomePage">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [SHOP TEST KIDS] but found [SHOP MENS]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [SHOP TEST KIDS] but found [SHOP MENS]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.prevail.shopnav.HomePage.TC00_HomePage_CategoryNavigation(HomePage.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC00_HomePage_CategoryNavigation -->
  <testcase name="TC04_HomePage_UI" time="5.111" classname="com.prevail.shopnav.HomePage"/>
  <testcase name="TC03_HomePage_HomePageSlideNavigation" time="13.597" classname="com.prevail.shopnav.HomePage"/>
  <testcase name="TC01_HomePage_SubCategoryNavigation" time="7.960" classname="com.prevail.shopnav.HomePage"/>
</testsuite> <!-- com.prevail.shopnav.HomePage -->
